x = float(input ("Εισάγετε σε μέτρα την απόσταση που θέλετε να μετατρέψετε:"))
y = float(x * 10)
print (str(y) + " δέκατα")
y = float(x * 100)
print (str(y) + " εκατοστά")
y = float(x * 1000)
print (str(y) + " χιλιοστά")
y = float(x / 1000)
print (str(y) + " χιλιόμετρα")